name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
categories:
  - title: '⚠️ Breaking'
    labels: ['breaking', 'semver:major']
  - title: '✨ Features'
    labels: ['feature', 'enhancement', 'semver:minor']
  - title: '🐞 Fixes'
    labels: ['bug', 'fix', 'semver:patch']
  - title: '🧰 Maintenance'
    labels: ['chore', 'refactor']
  - title: '📝 Docs'
    labels: ['docs']
  - title: '⚙️ CI'
    labels: ['ci']
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
autolabeler:
  - label: 'docs'
    files: ['docs/**', '**/*.rst', '**/*.md']
  - label: 'ci'
    files: ['.github/workflows/**']
  - label: 'feature'
    title:
      - '/^feat(\(.+\))?:/i'
  - label: 'fix'
    title:
      - '/^fix(\(.+\))?:/i'
version-resolver:
  major:
    labels: ['breaking','semver:major']
  minor:
    labels: ['feature','enhancement','semver:minor']
  patch:
    labels: ['fix','bug','semver:patch']
  default: patch